# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170816_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='at_company_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
