# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_workhistory_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=250)),
                ('school_location', models.CharField(max_length=250)),
                ('at_school_from', models.DateField(null=True)),
                ('at_school_till', models.DateField(blank=True, null=True)),
                ('present', models.BooleanField(default=False)),
                ('stream', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('github_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
