# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rootuser_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('comment', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
    ]
