# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rootuser_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rootuser',
            name='resume_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
