# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180323_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='rootuser',
            name='resume_url',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=main.models.CloudinaryStorage(), upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='rootuser',
            name='profile_photo',
            field=models.ImageField(storage=main.models.CloudinaryStorage(), upload_to=b'profile'),
        ),
        migrations.AlterField(
            model_name='rootuser',
            name='resume',
            field=models.FileField(default=b'resume/resume.pdf', storage=main.models.CloudinaryStorage(), upload_to=b'resume'),
        ),
    ]
