# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180328_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootuser',
            name='profile_photo_url',
        ),
    ]
